name: Sweepinghime
version: '1.0'
main: io.github.dashuxiadezhya.sweepinghime.Sweepinghime
authors: [凌寻]
description: 定期清理掉落物
website: https://www.minebbs.com/members/166623/
commands:
  linxun_cleanItem:
    usage: "/linxun_cleanItem [start|stop|clean|revise|reload|status|print]"