name: autoclean
version: '${project.version}'
main: io.github.dashuxiadezhya.sweepinghime.Autoclean
authors: [凌寻]
description: 自动清理掉落物
website: https://www.minebbs.com/members/166623/
log-prefix: §c[凌寻]
commands:
  linxun_cleanItem:
    usage: "/linxun_cleanItem [start|stop|clean|revise|reload|status|print]"